### PR TITLE
Eraser support

### LINKED ISSUE #60: Eraser support
There's nothing in the code with support for erasers. On the XP-Pen Artist Pro 16 drivers, you can flip your pen around to "draw" with the eraser on the top, which presses <kbd>E</kbd> in your art program (once the eraser is lifted the E is pressed again), as if it were a pencil.

From the official drivers:
image

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Closes #60

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Works as expected!


https://user-images.githubusercontent.com/44733677/189511437-c31311c4-dfa1-4f3c-a479-4af6bed7a3ed.mp4

**Comment by kurikaesu** [comment]
Thanks for trying to fix this. The eraser flashing is definitely a problem. It means the E key is being spammed. Not ideal as on slower computers it could lead to inconsistent eraser strokes.

What should probably happen and this needs testing is: detect when the eraser end of the pen is in proximity and send a keybind when entering and exiting proximity.

The keybinding would need to be customizable.

You will need to have the driver dump out the usb messages to see what it sends when entering and exiting proximity of the digitizer with the eraser end vs pen end.

My clean up commit shows how to get the usb debug messages back.

**Comment by ThatOneCalculator** [comment]
I'll work on that. As for customisability, I already made a PR on the GUI repo to add it :)

**Comment by ThatOneCalculator** [comment]
After some investigating, with
`Got transfer of data length: 12 data: 02:a8:28:40:d2:53:00:00:00:XX:00:00:`

<kbd>E</kbd> should be pressed once `XX` is >= 18

**Pull request closed without merging**
