### PR TITLE
add deco_pro_medium_wireless

### LINKED ISSUE #55: XP-Pen Deco Pro MW
Hello! Curious if you could add this device:

DEVICE ID: 28bd:0934
PRODUCT NAME: XP-Pen Deco Pro MW
PRODUCT PAGE: https://www.xp-pen.com/product/915.html

It's essentially the same as XP-Pen Deco Pro M, but in addition to the wired USB interface, it includes a wireless USB receiver and Bluetooth connectivity.

### PR DESCRIPTION
**Pull request by cstrahan-blueshift**
This works with the wired USB connection.

The USB receiver kinda sorta works, but it exhibits some strange behavior. For example, when starting up the daemon, the daemon acts as if the top left (assuming pad is in right handed drawing orientation) button is depressed -- with the default config, that results in the "b" key being held. To stop the "b" from being held, I can click the top right button resulting in (by default) an "e" key press. Now, if I click the top left button again, instead of a "b" key press event triggering, there's first a "b" key release followed by what seems to be a "b" key press (resulting in "b" auto repeating).

Here's an example of what `xev` reports:

```
KeyPress event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879796879, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XmbLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyRelease event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879796909, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyPress event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879796909, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XmbLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyRelease event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879796939, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyPress event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879796939, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XmbLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

<< TAPPED TOP RIGHT (E) KEY HERE>>
KeyPress event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879796970, (47,-20), root:(873,440),
    state 0x10, keycode 26 (keysym 0x65, e), same_screen YES,
    XLookupString gives 1 bytes: (65) "e"
    XmbLookupString gives 1 bytes: (65) "e"
    XFilterEvent returns: False

KeyRelease event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879797082, (47,-20), root:(873,440),
    state 0x10, keycode 26 (keysym 0x65, e), same_screen YES,
    XLookupString gives 1 bytes: (65) "e"
    XFilterEvent returns: False

<< TAPPED TOP LEFT (B) KEY HERE>>
KeyRelease event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879799115, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyPress event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879801012, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XmbLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyRelease event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879801513, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyPress event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879801513, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XmbLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyRelease event, serial 74, synthetic NO, window 0x3a00001,
    root 0x299, subw 0x0, time 2879801543, (47,-20), root:(873,440),
    state 0x10, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False
```

@kurikaesu if you'd be interested in taking a stab at fixing this when used wireless, I could buy you this model (if you'd add it to your Amazon wishlist).

Closes #55

### CODE REVIEW

**Comment by cstrahan-blueshift** [comment]
Another data point: if I tap the top right (b) button to kick off the "b" repeating events, and then tap the top right (e) button once to stop it, if I then tap the "b" button my my keyboard, no "b" character is typed into whatever text editor/entry I have focused. If I tap the "b" key on my keyboard a second time, this behaves as expected and a "b" is typed into my text editor.

So maybe something to do with either the order of key press/release events being backwards, or maybe one of the events missing entirely? :thinking:

**Comment by kurikaesu** [comment]
Thanks for the pull request! I've added this model to my wish list. I was actually expecting it to just work originally because the wired model is practically identical but it seems the wireless dongle presents itself differently.

I'm at the tail end of my house move (yay!) but I won't have internet connected until this Wednesday the 18th, assuming my ISP just needs to hook it up. Until then I'm a little limited on what I can do for PRs and testing.

**Comment by cstrahan-blueshift** [comment]
Hm... So, it turns out I can reproduce the repeating top left "b" button presses when using the wired USB connection as well -- I think I must have just not noticed.

> I'm at the tail end of my house move (yay!) 

Congrats!

I placed an order, should arrive at your address on Tuesday, May 17th :smile:

**Comment by kurikaesu** [comment]
Can you check if the package is delayed? I didn't receive anything yesterday unless it did arrive and I've become a victim of porch pirates :(

**Comment by cstrahan-blueshift** [comment]
Amazon says it was left at a hub -- I emailed you the details. 

Hope your move went well :slightly_smiling_face:

**Comment by cstrahan-blueshift** [comment]
Oops, I accidentally grabbed @[FXuZ](https://github.com/FXuZ)'s email address from one of their commits. I'm probably with unnecessary caution anyway, since anyone that sends you a gift from your wishlist would have access to that info anyway.

If you wouldn't mind, I can just drop a comment here with that info.

**Comment by kurikaesu** [comment]
All good, could you post just the order number? I just tried calling Amazon about it and they couldn't help unless I knew the order number or anything else related to the order

**Comment by cstrahan-blueshift** [comment]
ORDER # 111-3397026-2666617

**Comment by kurikaesu** [comment]
Thanks! Managed to sort things out. I'll be picking up the tablet tomorrow then I'll start looking into things

**Comment by kurikaesu** [comment]
Have the tablet in my hands. I can confirm that when attaching via bluetooth it immediately depresses B until I press something or use my keyboard to press something else. At any case, I'll merge this in and we can work on what is going on in bluetooth mode.

**Comment by kurikaesu** [comment]
Commit https://github.com/kurikaesu/userspace-tablet-driver-daemon/commit/64a1f042bd6b012a321c4a5c8b4b0d02f49d3fb6 should stop the B spam for now. I'd have to dig deeper into what exactly that message that is now being ignored actually means but for basic tablet functionality this will work ok

**Comment by kurikaesu** [comment]
After some pondering and checking out how the driver interface looks like on windows, I believe the message that I am ignoring now is actually providing a periodic status update on the battery capacity.

**Pull request merged**
